// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Randomize() {
  return window['go']['main']['App']['Randomize']();
}

export function SetCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCell'](arg1, arg2, arg3);
}

export function StartAutoPlay(arg1) {
  return window['go']['main']['App']['StartAutoPlay'](arg1);
}

export function Step() {
  return window['go']['main']['App']['Step']();
}

export function StopAutoPlay() {
  return window['go']['main']['App']['StopAutoPlay']();
}

export function ToggleCell(arg1, arg2) {
  return window['go']['main']['App']['ToggleCell'](arg1, arg2);
}
