// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Clear():Promise<main.GameState>;

export function GetState():Promise<main.GameState>;

export function Randomize():Promise<main.GameState>;

export function SetCell(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function StartAutoPlay(arg1:number):Promise<void>;

export function Step():Promise<main.GameState>;

export function StopAutoPlay():Promise<main.GameState>;

export function ToggleCell(arg1:number,arg2:number):Promise<main.GameState>;
